 const patientData = [
    {
        id:1,
        patientId:100,
        name:"Antony",
        hospital:"St.Richards",
        billData:{
            wheelChair:5,
            bed:15,
            ambulance:20,
            pharma:50,
            xRay:10
        }
    },
    {
        id:2,
        patientId:101,
        name:"Elanga",
        hospital:"St.Richards",
        billData:{
            wheelChair:5,
            bed:15,
            ambulance:20,
            pharma:50,
            xRay:10
        }
    },
    {
        id:3,
        patientId:103,
        name:"Robert",
        hospital:"St.Richards",
        billData:{
            wheelChair:5,
            bed:15,
            ambulance:20,
            pharma:50,
            xRay:10
        }
    },
    {
        id:4,
        patientId:104,
        name:"Perry",
        hospital:"St.Richards",
        billData:{
            wheelChair:5,
            bed:15,
            ambulance:20,
            pharma:50,
            xRay:10
        }
    },
    {
        id:5,
        patientId:105,
        name:"Emma",
        hospital:"St.Richards",
        billData:{
            wheelChair:15,
            bed:10,
            ambulance:10,
            pharma:10,
            xRay:10
        }
    },
    {
        id:1,
        patientId:100,
        name:"Antony",
        hospital:"St.Richards",
        billData:{
            wheelChair:5,
            bed:15,
            ambulance:20,
            pharma:50,
            xRay:10
        }
    },
    {
        id:1,
        patientId:100,
        name:"Antony",
        hospital:"St.Richards",
        billData:{
            wheelChair:5,
            bed:15,
            ambulance:20,
            pharma:50,
            xRay:10
        }
    },
    {
        id:1,
        patientId:100,
        name:"Antony",
        hospital:"St.Richards",
        billData:{
            wheelChair:5,
            bed:15,
            ambulance:20,
            pharma:50,
            xRay:10
        }
    },
    {
        id:1,
        patientId:100,
        name:"Antony",
        hospital:"St.Richards",
        billData:{
            wheelChair:5,
            bed:15,
            ambulance:20,
            pharma:50,
            xRay:10
        }
    }
]